- name: Upload Arnika bin directory
  ansible.builtin.copy:
    src: "bin/arnika"
    dest: "/opt/"
    owner: root
    group: root
    mode: "0775"

- name: Create Arnika config dir
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: "0700"
    path: "/etc/arnika"

- name: Create KMS ETSI014 certificate directory
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    mode: "0700"
    path: "{{ kms_cert_dir }}/kms"

- name: Upload KMS ETSI04 certificates
  ansible.builtin.copy:
    src: "certs/{{ item }}"
    dest: "{{ kms_cert_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  with_items:
    - "{{kms_my_name}}.csr"
    - "{{kms_my_name}}.crt"
    - "{{kms_my_name}}.key"
    - "{{kms_ca_file}}.pem"

- name: deploy environment file
  ansible.builtin.template:
    src: "arnika/arnika.env.j2"
    dest: "/etc/arnika/arnika.env"
    owner: root
    group: root
    mode: "0600"

- name: Deploy Arnika Systemd Unit file config
  ansible.builtin.copy:
    src: "arnika/arnika.service"
    dest: "/etc/systemd/system/arnika.service"
    owner: root
    group: root
    mode: "0664"

- name: Allow Arnika port in firewalld
  ansible.posix.firewalld:
    port: "{{ arnika_listen.split(':')[1] }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  when:
    arnika_listen is defined and arnika_listen.split(":")[0] == "0.0.0.0"
  notify:
    - Reload firewalld
